name: Django CI

on:
  push:
    branches:
      - '*' # Runs tests on all branches
  pull_request:
    branches:
      - '*' # Also runs tests on pull requests to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16  # Use Postgres for the database, adjust if you're using a different one
        ports:
          - 5432:5432
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'  # You can specify your preferred Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies

    - name: Set up the database
      run: |
        python manage.py migrate  # Run migrations to set up the database schema

    - name: Run tests
      run: |
        python manage.py test